language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "stable"
befor_install:
  - stty cols 80



dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
      -google-chrome
    package:
      -google-chrome-stable fluxbox

before_script:
  - npm prune
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>1 &
script:

  - npm run test
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
